from __future__ import annotations

"""
masxai/protocol.py - wire protocol for the MASXAI forecasting subnet.

The validator fills the request fields and queries miners. Each miner returns a
structured binary forecast generated by its forecasting engine.
"""

from enum import Enum
from typing import Any, Optional

import pydantic

from masxai.bt_compat import bt

SYNAPSE_VERSION = 3


class ForecastEventType(str, Enum):
    TAO_PRICE_MOVEMENT = "tao_price_movement"
    SUBNET_TOKEN_PRICE = "subnet_token_price"
    NEW_SUBNET_REGISTRATION = "new_subnet_registration"
    GOVERNANCE_OUTCOME = "governance_outcome"
    ECOSYSTEM_GROWTH_METRIC = "ecosystem_growth_metric"
    SIGNIFICANT_BITTENSOR_EVENT = "significant_bittensor_event"


class ForecastSynapse(bt.Synapse):
    """
    A single binary forecasting task.

    Request (set by validator):
        forecast_id     per-issue task id issued by the validator
        question_id     upstream BT-Forecast prediction id, when applicable
        question_key    canonical BT-Forecast question match key
        question        human-readable binary question
        event_type      one of ForecastEventType
        family          BT-Forecast family/category, e.g. active_miners
        scope           subnet | network | market
        netuid          target subnet uid, when applicable
        horizon_days    BT-Forecast horizon in days
        asset           oracle id of the asset, when applicable
        reference_value objective value at issue time, when applicable
        reference_metadata additional issue-time state
        forecast_window compact horizon label such as "1h" or "24h"
        issued_at       unix seconds when issued
        resolve_at      unix seconds when the question resolves
        context         validator-provided context for the miner
        version         protocol version

    Response (set by miner):
        probability     P(YES) in [0, 1], primary Phase-1 score input
        prediction      binary YES/NO forecast
        confidence      confidence in [0, 1]
        reasoning       concise AI reasoning summary
        timestamp       ISO8601 generation timestamp
        model           forecasting model label, e.g. gemini-2.5-pro
        features        optional miner-reported signals/features
    """

    # ---- request ----
    forecast_id: str = ""
    question_id: str = ""
    question_key: str = ""
    question: str = ""
    event_type: str = ForecastEventType.TAO_PRICE_MOVEMENT.value
    family: str = ""
    scope: str = ""
    netuid: Optional[int] = None
    horizon_days: Optional[int] = None
    asset: str = "bittensor"
    reference_value: Optional[float] = None
    reference_metadata: dict[str, Any] = pydantic.Field(default_factory=dict)
    forecast_window: str = "1h"
    issued_at: float = 0.0
    resolve_at: float = 0.0
    context: str = ""
    version: int = SYNAPSE_VERSION

    # ---- response ----
    prediction: Optional[bool] = pydantic.Field(default=None)
    confidence: Optional[float] = pydantic.Field(default=None)
    reasoning: str = ""
    timestamp: str = ""
    model: str = ""
    probability: Optional[float] = pydantic.Field(default=None)
    features: dict[str, Any] = pydantic.Field(default_factory=dict)

    def deserialize(self) -> dict[str, Any]:
        """Validators call this to read the miner's answer."""
        return {
            "forecast_id": self.forecast_id,
            "question_id": self.question_id,
            "question_key": self.question_key,
            "event_type": self.event_type,
            "family": self.family,
            "scope": self.scope,
            "netuid": self.netuid,
            "horizon_days": self.horizon_days,
            "probability": self.probability,
            "prediction": self.prediction,
            "confidence": self.confidence,
            "forecast_window": self.forecast_window,
            "reasoning": self.reasoning,
            "timestamp": self.timestamp,
            "model": self.model,
            "features": self.features,
        }
